version: "3"
services:
  #mssql docker
  ecinema-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - ecinemanet

  ecinema-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=ecinema-sql,1433;Database=eCinema;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      
    ports:
      - 5192:5192
    networks:
      - ecinemanet
    links:
      - ecinema-sql
    depends_on:
      - ecinema-sql    
  
networks:
  ecinemanet:
    driver: bridge